package com.thuanthichlaptrinh.card_words.entrypoint.dto.request.offline;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OfflineGameSessionRequest {
    private String sessionId; // UUID generated by client
    private Long gameId;
    private String startedAt; // ISO 8601
    private String finishedAt; // ISO 8601
    private Integer totalQuestions;
    private Integer correctCount;
    private Integer score;

    // Details embedded
    private List<OfflineGameDetailRequest> details;
}
