server:
    port: 8080

spring:
    application:
        name: card-words

    datasource:
        url: jdbc:postgresql://localhost:5432/card_words
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
        open-in-view: false

    data:
        redis:
            host: localhost
            port: 6379
            password:
            timeout: 60000

    cache:
        type: redis
        redis:
            time-to-live: 3600000 # 1h

    mail:
        host: smtp.gmail.com
        port: 587
        username: thuanthichlaptrinh@gmail.com
        password: jcdfsqryziswpjfw
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        trust: smtp.gmail.com
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

# JWT Configuration
jwt:
    secret-key: Y2FyZC13b3Jkcy1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbg==
    expiration: 86400000 # 24h
    refresh-token:
        expiration: 604800000 # 7d

activation:
    expired-time: 86400000 # 24h
    resend-interval: 300000 # 5m

logging:
    level:
        org:
            springframework:
                security: trace
        com:
            thuanthichlaptrinh: debug

http:
    request-logging-filter:
        enabled: true
        include-payload: true
