server:
    port: 8080

spring:
    application:
        name: card-words

    # PostgreSQL Configuration
    datasource:
        url: jdbc:postgresql://localhost:5432/card_words
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver

    # JPA Configuration
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
        open-in-view: false

    # Redis Configuration
    data:
        redis:
            host: localhost
            port: 6379
            password:
            timeout: 60000

    # Cache Configuration
    cache:
        type: redis
        redis:
            time-to-live: 3600000 # 1 hour in milliseconds

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

# Logging
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
