server:
    port: ${SERVER_PORT}

spring:
    application:
        name: card-words

    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
        open-in-view: false

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
            timeout: 60000

    cache:
        type: redis
        redis:
            time-to-live: 3600000

    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        trust: smtp.gmail.com
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

# JWT Configuration
jwt:
    secret-key: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION_TIME}
    refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

activation:
    expired-time: ${ACTIVATION_EXPIRED_TIME}
    resend-interval: ${ACTIVATION_RESEND_INTERVAL}

google:
    oauth2:
        client-id: ${GOOGLE_OAUTH_CLIENT_ID}
        client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
        redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}

logging:
    level:
        org:
            springframework:
                security: trace
        com:
            thuanthichlaptrinh: debug

http:
    request-logging-filter:
        enabled: true
        include-payload: true
