-- V2: Remove unique constraint from topic_id in vocab table
-- This allows multiple vocabs to share the same topic (Many-to-One relationship)

-- Drop the unique constraint if it exists
DO $$
DECLARE
    r RECORD;
BEGIN
    -- Try to drop the unique constraint by constraint name
    -- Common constraint names generated by Hibernate
    IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'uk_vocab_topic_id' 
        AND conrelid = 'vocab'::regclass
    ) THEN
        ALTER TABLE vocab DROP CONSTRAINT uk_vocab_topic_id;
    END IF;

    -- Drop all unique constraints containing 'topic_id'
    FOR r IN (
        SELECT conname 
        FROM pg_constraint 
        WHERE conname LIKE '%topic_id%' 
        AND conrelid = 'vocab'::regclass
        AND contype = 'u'
    ) LOOP
        EXECUTE 'ALTER TABLE vocab DROP CONSTRAINT ' || quote_ident(r.conname);
    END LOOP;

    -- Drop unique indexes if exists
    FOR r IN (
        SELECT indexname 
        FROM pg_indexes 
        WHERE indexname LIKE '%topic_id%' 
        AND tablename = 'vocab'
        AND indexdef LIKE '%UNIQUE%'
    ) LOOP
        EXECUTE 'DROP INDEX IF EXISTS ' || quote_ident(r.indexname);
    END LOOP;
END $$;

-- Add a regular (non-unique) index on topic_id for better query performance
CREATE INDEX IF NOT EXISTS idx_vocab_topic_id ON vocab(topic_id);

-- Verify the change
SELECT 
    CASE 
        WHEN COUNT(*) = 0 THEN 'SUCCESS: No unique constraint on topic_id'
        ELSE 'WARNING: Unique constraint still exists on topic_id'
    END as status
FROM pg_constraint 
WHERE conname LIKE '%topic_id%' 
AND conrelid = 'vocab'::regclass
AND contype = 'u';
